parameters:
    database_type: mysql
    database_name: noval_book
    server: 127.0.0.1
    username: root
    password: null
    charset: utf8
    port: 3306
    option:
        8 : 0
    env: dev
    telegram: https://integram.org/cuxI45cnZEw

wechat:
    debug: false
    app_id: wx78d6a8ffc673a76f
    secret: ec4c0b88ec705e122ed27cadbb160fa2
    token: dinc902n1nki29kso90
    aes_key: null
    log:
        level: debug
        file: /Users/will/php_productions/will-wizmacau/logs/easywechat.log